// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/cory-johannsen/mud/internal/config"
	"github.com/cory-johannsen/mud/internal/frontend/handlers"
	"github.com/cory-johannsen/mud/internal/frontend/telnet"
	"github.com/cory-johannsen/mud/internal/game/ruleset"
	"github.com/cory-johannsen/mud/internal/storage/postgres"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// Initialize is the wire-generated injector for the devserver binary.
func Initialize(ctx context.Context, cfg *AppConfig, logger *zap.Logger) (*App, error) {
	databaseConfig := AppConfigToDatabase(cfg)
	pool, err := postgres.NewPool(ctx, databaseConfig)
	if err != nil {
		return nil, err
	}
	telnetConfig := AppConfigToTelnet(cfg)
	pgxpoolPool := postgres.PoolDB(pool)
	accountRepository := postgres.NewAccountRepository(pgxpoolPool)
	characterRepository := postgres.NewCharacterRepository(pgxpoolPool)
	regionsDir := cfg.RegionsDir
	v, err := ruleset.LoadAllRegionsSlice(regionsDir, logger)
	if err != nil {
		return nil, err
	}
	teamsDir := cfg.TeamsDir
	v2, err := ruleset.LoadAllTeams(teamsDir, logger)
	if err != nil {
		return nil, err
	}
	jobsDir := cfg.JobsDir
	v3, err := ruleset.LoadAllJobsSlice(jobsDir, logger)
	if err != nil {
		return nil, err
	}
	archetypesDir := cfg.ArchetypesDir
	v4, err := ruleset.LoadAllArchetypesSlice(archetypesDir, logger)
	if err != nil {
		return nil, err
	}
	string2 := AppConfigToGameServerAddr(cfg)
	skillsFile := cfg.SkillsFile
	v5, err := ruleset.LoadAllSkills(skillsFile, logger)
	if err != nil {
		return nil, err
	}
	characterSkillsRepository := postgres.NewCharacterSkillsRepository(pgxpoolPool)
	featsFile := cfg.FeatsFile
	v6, err := ruleset.LoadAllFeats(featsFile, logger)
	if err != nil {
		return nil, err
	}
	characterFeatsRepository := postgres.NewCharacterFeatsRepository(pgxpoolPool)
	classFeaturesFile := cfg.ClassFeatsFile
	v7, err := ruleset.LoadAllClassFeatures(classFeaturesFile, logger)
	if err != nil {
		return nil, err
	}
	characterClassFeaturesRepository := postgres.NewCharacterClassFeaturesRepository(pgxpoolPool)
	authHandler := handlers.NewAuthHandler(accountRepository, characterRepository, v, v2, v3, v4, logger, string2, telnetConfig, v5, characterSkillsRepository, v6, characterFeatsRepository, v7, characterClassFeaturesRepository)
	acceptor := telnet.NewAcceptor(telnetConfig, authHandler, logger)
	app := &App{
		Pool:           pool,
		TelnetAcceptor: acceptor,
	}
	return app, nil
}

// wire.go:

// AppConfig holds CLI flag values for the devserver binary.
type AppConfig struct {
	Config         config.Config
	RegionsDir     ruleset.RegionsDir
	TeamsDir       ruleset.TeamsDir
	JobsDir        ruleset.JobsDir
	ArchetypesDir  ruleset.ArchetypesDir
	SkillsFile     ruleset.SkillsFile
	FeatsFile      ruleset.FeatsFile
	ClassFeatsFile ruleset.ClassFeaturesFile
}

// App holds top-level components for the devserver binary.
type App struct {
	Pool           *postgres.Pool
	TelnetAcceptor *telnet.Acceptor
}

// AppConfigToDatabase extracts database config for wire.
func AppConfigToDatabase(cfg *AppConfig) config.DatabaseConfig {
	return cfg.Config.Database
}

// AppConfigToTelnet extracts telnet config for wire.
func AppConfigToTelnet(cfg *AppConfig) config.TelnetConfig {
	return cfg.Config.Telnet
}

// AppConfigToGameServerAddr extracts the game server address string for wire.
func AppConfigToGameServerAddr(cfg *AppConfig) string {
	return cfg.Config.GameServer.Addr()
}
