// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: game/v1/game.proto

package gamev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType distinguishes between say and emote messages.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_SAY         MessageType = 1
	MessageType_MESSAGE_TYPE_EMOTE       MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_SAY",
		2: "MESSAGE_TYPE_EMOTE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_SAY":         1,
		"MESSAGE_TYPE_EMOTE":       2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{0}
}

// RoomEventType distinguishes arrival from departure.
type RoomEventType int32

const (
	RoomEventType_ROOM_EVENT_TYPE_UNSPECIFIED RoomEventType = 0
	RoomEventType_ROOM_EVENT_TYPE_ARRIVE      RoomEventType = 1
	RoomEventType_ROOM_EVENT_TYPE_DEPART      RoomEventType = 2
)

// Enum value maps for RoomEventType.
var (
	RoomEventType_name = map[int32]string{
		0: "ROOM_EVENT_TYPE_UNSPECIFIED",
		1: "ROOM_EVENT_TYPE_ARRIVE",
		2: "ROOM_EVENT_TYPE_DEPART",
	}
	RoomEventType_value = map[string]int32{
		"ROOM_EVENT_TYPE_UNSPECIFIED": 0,
		"ROOM_EVENT_TYPE_ARRIVE":      1,
		"ROOM_EVENT_TYPE_DEPART":      2,
	}
)

func (x RoomEventType) Enum() *RoomEventType {
	p := new(RoomEventType)
	*p = x
	return p
}

func (x RoomEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[1].Descriptor()
}

func (RoomEventType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[1]
}

func (x RoomEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomEventType.Descriptor instead.
func (RoomEventType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{1}
}

// ClientMessage wraps all client-to-server commands.
type ClientMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_JoinWorld
	//	*ClientMessage_Move
	//	*ClientMessage_Look
	//	*ClientMessage_Say
	//	*ClientMessage_Emote
	//	*ClientMessage_Who
	//	*ClientMessage_Exits
	//	*ClientMessage_Quit
	//	*ClientMessage_Examine
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_game_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetJoinWorld() *JoinWorldRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_JoinWorld); ok {
			return x.JoinWorld
		}
	}
	return nil
}

func (x *ClientMessage) GetMove() *MoveRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *ClientMessage) GetLook() *LookRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Look); ok {
			return x.Look
		}
	}
	return nil
}

func (x *ClientMessage) GetSay() *SayRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Say); ok {
			return x.Say
		}
	}
	return nil
}

func (x *ClientMessage) GetEmote() *EmoteRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Emote); ok {
			return x.Emote
		}
	}
	return nil
}

func (x *ClientMessage) GetWho() *WhoRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Who); ok {
			return x.Who
		}
	}
	return nil
}

func (x *ClientMessage) GetExits() *ExitsRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Exits); ok {
			return x.Exits
		}
	}
	return nil
}

func (x *ClientMessage) GetQuit() *QuitRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Quit); ok {
			return x.Quit
		}
	}
	return nil
}

func (x *ClientMessage) GetExamine() *ExamineRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Examine); ok {
			return x.Examine
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_JoinWorld struct {
	JoinWorld *JoinWorldRequest `protobuf:"bytes,2,opt,name=join_world,json=joinWorld,proto3,oneof"`
}

type ClientMessage_Move struct {
	Move *MoveRequest `protobuf:"bytes,3,opt,name=move,proto3,oneof"`
}

type ClientMessage_Look struct {
	Look *LookRequest `protobuf:"bytes,4,opt,name=look,proto3,oneof"`
}

type ClientMessage_Say struct {
	Say *SayRequest `protobuf:"bytes,5,opt,name=say,proto3,oneof"`
}

type ClientMessage_Emote struct {
	Emote *EmoteRequest `protobuf:"bytes,6,opt,name=emote,proto3,oneof"`
}

type ClientMessage_Who struct {
	Who *WhoRequest `protobuf:"bytes,7,opt,name=who,proto3,oneof"`
}

type ClientMessage_Exits struct {
	Exits *ExitsRequest `protobuf:"bytes,8,opt,name=exits,proto3,oneof"`
}

type ClientMessage_Quit struct {
	Quit *QuitRequest `protobuf:"bytes,9,opt,name=quit,proto3,oneof"`
}

type ClientMessage_Examine struct {
	Examine *ExamineRequest `protobuf:"bytes,10,opt,name=examine,proto3,oneof"`
}

func (*ClientMessage_JoinWorld) isClientMessage_Payload() {}

func (*ClientMessage_Move) isClientMessage_Payload() {}

func (*ClientMessage_Look) isClientMessage_Payload() {}

func (*ClientMessage_Say) isClientMessage_Payload() {}

func (*ClientMessage_Emote) isClientMessage_Payload() {}

func (*ClientMessage_Who) isClientMessage_Payload() {}

func (*ClientMessage_Exits) isClientMessage_Payload() {}

func (*ClientMessage_Quit) isClientMessage_Payload() {}

func (*ClientMessage_Examine) isClientMessage_Payload() {}

// ServerEvent wraps all server-to-client events.
type ServerEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerEvent_RoomView
	//	*ServerEvent_Message
	//	*ServerEvent_RoomEvent
	//	*ServerEvent_PlayerList
	//	*ServerEvent_ExitList
	//	*ServerEvent_Error
	//	*ServerEvent_Disconnected
	//	*ServerEvent_CharacterInfo
	//	*ServerEvent_NpcView
	Payload       isServerEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_game_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *ServerEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerEvent) GetPayload() isServerEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerEvent) GetRoomView() *RoomView {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_RoomView); ok {
			return x.RoomView
		}
	}
	return nil
}

func (x *ServerEvent) GetMessage() *MessageEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomEvent() *RoomEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_RoomEvent); ok {
			return x.RoomEvent
		}
	}
	return nil
}

func (x *ServerEvent) GetPlayerList() *PlayerList {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_PlayerList); ok {
			return x.PlayerList
		}
	}
	return nil
}

func (x *ServerEvent) GetExitList() *ExitList {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_ExitList); ok {
			return x.ExitList
		}
	}
	return nil
}

func (x *ServerEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerEvent) GetDisconnected() *Disconnected {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_Disconnected); ok {
			return x.Disconnected
		}
	}
	return nil
}

func (x *ServerEvent) GetCharacterInfo() *CharacterInfo {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_CharacterInfo); ok {
			return x.CharacterInfo
		}
	}
	return nil
}

func (x *ServerEvent) GetNpcView() *NpcView {
	if x != nil {
		if x, ok := x.Payload.(*ServerEvent_NpcView); ok {
			return x.NpcView
		}
	}
	return nil
}

type isServerEvent_Payload interface {
	isServerEvent_Payload()
}

type ServerEvent_RoomView struct {
	RoomView *RoomView `protobuf:"bytes,2,opt,name=room_view,json=roomView,proto3,oneof"`
}

type ServerEvent_Message struct {
	Message *MessageEvent `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type ServerEvent_RoomEvent struct {
	RoomEvent *RoomEvent `protobuf:"bytes,4,opt,name=room_event,json=roomEvent,proto3,oneof"`
}

type ServerEvent_PlayerList struct {
	PlayerList *PlayerList `protobuf:"bytes,5,opt,name=player_list,json=playerList,proto3,oneof"`
}

type ServerEvent_ExitList struct {
	ExitList *ExitList `protobuf:"bytes,6,opt,name=exit_list,json=exitList,proto3,oneof"`
}

type ServerEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type ServerEvent_Disconnected struct {
	Disconnected *Disconnected `protobuf:"bytes,8,opt,name=disconnected,proto3,oneof"`
}

type ServerEvent_CharacterInfo struct {
	CharacterInfo *CharacterInfo `protobuf:"bytes,9,opt,name=character_info,json=characterInfo,proto3,oneof"`
}

type ServerEvent_NpcView struct {
	NpcView *NpcView `protobuf:"bytes,10,opt,name=npc_view,json=npcView,proto3,oneof"`
}

func (*ServerEvent_RoomView) isServerEvent_Payload() {}

func (*ServerEvent_Message) isServerEvent_Payload() {}

func (*ServerEvent_RoomEvent) isServerEvent_Payload() {}

func (*ServerEvent_PlayerList) isServerEvent_Payload() {}

func (*ServerEvent_ExitList) isServerEvent_Payload() {}

func (*ServerEvent_Error) isServerEvent_Payload() {}

func (*ServerEvent_Disconnected) isServerEvent_Payload() {}

func (*ServerEvent_CharacterInfo) isServerEvent_Payload() {}

func (*ServerEvent_NpcView) isServerEvent_Payload() {}

// JoinWorldRequest is sent by the client to enter the game world after authentication.
type JoinWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CharacterId   int64                  `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterName string                 `protobuf:"bytes,4,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	CurrentHp     int32                  `protobuf:"varint,5,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinWorldRequest) Reset() {
	*x = JoinWorldRequest{}
	mi := &file_game_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorldRequest) ProtoMessage() {}

func (x *JoinWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorldRequest.ProtoReflect.Descriptor instead.
func (*JoinWorldRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *JoinWorldRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *JoinWorldRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JoinWorldRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *JoinWorldRequest) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *JoinWorldRequest) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

// MoveRequest asks the server to move the player in the given direction.
type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_game_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *MoveRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

// LookRequest asks the server for the current room description.
type LookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookRequest) Reset() {
	*x = LookRequest{}
	mi := &file_game_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookRequest) ProtoMessage() {}

func (x *LookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookRequest.ProtoReflect.Descriptor instead.
func (*LookRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{4}
}

// SayRequest sends a chat message to all players in the same room.
type SayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayRequest) Reset() {
	*x = SayRequest{}
	mi := &file_game_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayRequest) ProtoMessage() {}

func (x *SayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayRequest.ProtoReflect.Descriptor instead.
func (*SayRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *SayRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// EmoteRequest sends an emote action to all players in the same room.
type EmoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmoteRequest) Reset() {
	*x = EmoteRequest{}
	mi := &file_game_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmoteRequest) ProtoMessage() {}

func (x *EmoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmoteRequest.ProtoReflect.Descriptor instead.
func (*EmoteRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *EmoteRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// WhoRequest asks for the list of players in the current room.
type WhoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoRequest) Reset() {
	*x = WhoRequest{}
	mi := &file_game_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoRequest) ProtoMessage() {}

func (x *WhoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoRequest.ProtoReflect.Descriptor instead.
func (*WhoRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{7}
}

// ExitsRequest asks for the list of exits from the current room.
type ExitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitsRequest) Reset() {
	*x = ExitsRequest{}
	mi := &file_game_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitsRequest) ProtoMessage() {}

func (x *ExitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitsRequest.ProtoReflect.Descriptor instead.
func (*ExitsRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{8}
}

// QuitRequest signals the client wants to disconnect.
type QuitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitRequest) Reset() {
	*x = QuitRequest{}
	mi := &file_game_v1_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRequest) ProtoMessage() {}

func (x *QuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRequest.ProtoReflect.Descriptor instead.
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{9}
}

// RoomView describes the player's current room.
type RoomView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Exits         []*ExitInfo            `protobuf:"bytes,4,rep,name=exits,proto3" json:"exits,omitempty"`
	Players       []string               `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	Npcs          []*NpcInfo             `protobuf:"bytes,6,rep,name=npcs,proto3" json:"npcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomView) Reset() {
	*x = RoomView{}
	mi := &file_game_v1_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomView) ProtoMessage() {}

func (x *RoomView) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomView.ProtoReflect.Descriptor instead.
func (*RoomView) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{10}
}

func (x *RoomView) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomView) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomView) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoomView) GetExits() []*ExitInfo {
	if x != nil {
		return x.Exits
	}
	return nil
}

func (x *RoomView) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomView) GetNpcs() []*NpcInfo {
	if x != nil {
		return x.Npcs
	}
	return nil
}

// ExitInfo describes a single exit from a room.
type ExitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	TargetRoomId  string                 `protobuf:"bytes,2,opt,name=target_room_id,json=targetRoomId,proto3" json:"target_room_id,omitempty"`
	Locked        bool                   `protobuf:"varint,3,opt,name=locked,proto3" json:"locked,omitempty"`
	Hidden        bool                   `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitInfo) Reset() {
	*x = ExitInfo{}
	mi := &file_game_v1_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitInfo) ProtoMessage() {}

func (x *ExitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitInfo.ProtoReflect.Descriptor instead.
func (*ExitInfo) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{11}
}

func (x *ExitInfo) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ExitInfo) GetTargetRoomId() string {
	if x != nil {
		return x.TargetRoomId
	}
	return ""
}

func (x *ExitInfo) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *ExitInfo) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

// MessageEvent delivers a chat message or emote from another player.
type MessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=game.v1.MessageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_game_v1_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{12}
}

func (x *MessageEvent) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MessageEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageEvent) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

// RoomEvent notifies about player arrivals and departures.
type RoomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        string                 `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Type          RoomEventType          `protobuf:"varint,2,opt,name=type,proto3,enum=game.v1.RoomEventType" json:"type,omitempty"`
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEvent) Reset() {
	*x = RoomEvent{}
	mi := &file_game_v1_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent) ProtoMessage() {}

func (x *RoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent.ProtoReflect.Descriptor instead.
func (*RoomEvent) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{13}
}

func (x *RoomEvent) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *RoomEvent) GetType() RoomEventType {
	if x != nil {
		return x.Type
	}
	return RoomEventType_ROOM_EVENT_TYPE_UNSPECIFIED
}

func (x *RoomEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

// PlayerList contains the players in the current room.
type PlayerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomTitle     string                 `protobuf:"bytes,1,opt,name=room_title,json=roomTitle,proto3" json:"room_title,omitempty"`
	Players       []string               `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerList) Reset() {
	*x = PlayerList{}
	mi := &file_game_v1_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerList) ProtoMessage() {}

func (x *PlayerList) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerList.ProtoReflect.Descriptor instead.
func (*PlayerList) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerList) GetRoomTitle() string {
	if x != nil {
		return x.RoomTitle
	}
	return ""
}

func (x *PlayerList) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

// ExitList contains the exits from the current room.
type ExitList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exits         []*ExitInfo            `protobuf:"bytes,1,rep,name=exits,proto3" json:"exits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitList) Reset() {
	*x = ExitList{}
	mi := &file_game_v1_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitList) ProtoMessage() {}

func (x *ExitList) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitList.ProtoReflect.Descriptor instead.
func (*ExitList) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{15}
}

func (x *ExitList) GetExits() []*ExitInfo {
	if x != nil {
		return x.Exits
	}
	return nil
}

// ErrorEvent delivers an error message to the client.
type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_game_v1_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{16}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Disconnected signals the server is closing the session.
type Disconnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnected) Reset() {
	*x = Disconnected{}
	mi := &file_game_v1_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnected) ProtoMessage() {}

func (x *Disconnected) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnected.ProtoReflect.Descriptor instead.
func (*Disconnected) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{17}
}

func (x *Disconnected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CharacterInfo is sent to the client on session join to display character stats.
type CharacterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Class         string                 `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Experience    int32                  `protobuf:"varint,6,opt,name=experience,proto3" json:"experience,omitempty"`
	MaxHp         int32                  `protobuf:"varint,7,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	CurrentHp     int32                  `protobuf:"varint,8,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	Strength      int32                  `protobuf:"varint,9,opt,name=strength,proto3" json:"strength,omitempty"`
	Dexterity     int32                  `protobuf:"varint,10,opt,name=dexterity,proto3" json:"dexterity,omitempty"`
	Constitution  int32                  `protobuf:"varint,11,opt,name=constitution,proto3" json:"constitution,omitempty"`
	Intelligence  int32                  `protobuf:"varint,12,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Wisdom        int32                  `protobuf:"varint,13,opt,name=wisdom,proto3" json:"wisdom,omitempty"`
	Charisma      int32                  `protobuf:"varint,14,opt,name=charisma,proto3" json:"charisma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterInfo) Reset() {
	*x = CharacterInfo{}
	mi := &file_game_v1_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterInfo) ProtoMessage() {}

func (x *CharacterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterInfo.ProtoReflect.Descriptor instead.
func (*CharacterInfo) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{18}
}

func (x *CharacterInfo) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CharacterInfo) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CharacterInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharacterInfo) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *CharacterInfo) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *CharacterInfo) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *CharacterInfo) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *CharacterInfo) GetDexterity() int32 {
	if x != nil {
		return x.Dexterity
	}
	return 0
}

func (x *CharacterInfo) GetConstitution() int32 {
	if x != nil {
		return x.Constitution
	}
	return 0
}

func (x *CharacterInfo) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *CharacterInfo) GetWisdom() int32 {
	if x != nil {
		return x.Wisdom
	}
	return 0
}

func (x *CharacterInfo) GetCharisma() int32 {
	if x != nil {
		return x.Charisma
	}
	return 0
}

// NpcInfo summarises an NPC visible in the room.
type NpcInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcInfo) Reset() {
	*x = NpcInfo{}
	mi := &file_game_v1_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcInfo) ProtoMessage() {}

func (x *NpcInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcInfo.ProtoReflect.Descriptor instead.
func (*NpcInfo) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{19}
}

func (x *NpcInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NpcInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ExamineRequest asks the server for detail on a named target.
type ExamineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamineRequest) Reset() {
	*x = ExamineRequest{}
	mi := &file_game_v1_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamineRequest) ProtoMessage() {}

func (x *ExamineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamineRequest.ProtoReflect.Descriptor instead.
func (*ExamineRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{20}
}

func (x *ExamineRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// NpcView delivers detailed NPC information in response to examine.
type NpcView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstanceId        string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	HealthDescription string                 `protobuf:"bytes,4,opt,name=health_description,json=healthDescription,proto3" json:"health_description,omitempty"`
	Level             int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NpcView) Reset() {
	*x = NpcView{}
	mi := &file_game_v1_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcView) ProtoMessage() {}

func (x *NpcView) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcView.ProtoReflect.Descriptor instead.
func (*NpcView) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{21}
}

func (x *NpcView) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NpcView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NpcView) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NpcView) GetHealthDescription() string {
	if x != nil {
		return x.HealthDescription
	}
	return ""
}

func (x *NpcView) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_game_v1_game_proto protoreflect.FileDescriptor

const file_game_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x12game/v1/game.proto\x12\agame.v1\"\xde\x03\n" +
	"\rClientMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12:\n" +
	"\n" +
	"join_world\x18\x02 \x01(\v2\x19.game.v1.JoinWorldRequestH\x00R\tjoinWorld\x12*\n" +
	"\x04move\x18\x03 \x01(\v2\x14.game.v1.MoveRequestH\x00R\x04move\x12*\n" +
	"\x04look\x18\x04 \x01(\v2\x14.game.v1.LookRequestH\x00R\x04look\x12'\n" +
	"\x03say\x18\x05 \x01(\v2\x13.game.v1.SayRequestH\x00R\x03say\x12-\n" +
	"\x05emote\x18\x06 \x01(\v2\x15.game.v1.EmoteRequestH\x00R\x05emote\x12'\n" +
	"\x03who\x18\a \x01(\v2\x13.game.v1.WhoRequestH\x00R\x03who\x12-\n" +
	"\x05exits\x18\b \x01(\v2\x15.game.v1.ExitsRequestH\x00R\x05exits\x12*\n" +
	"\x04quit\x18\t \x01(\v2\x14.game.v1.QuitRequestH\x00R\x04quit\x123\n" +
	"\aexamine\x18\n" +
	" \x01(\v2\x17.game.v1.ExamineRequestH\x00R\aexamineB\t\n" +
	"\apayload\"\x95\x04\n" +
	"\vServerEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x120\n" +
	"\troom_view\x18\x02 \x01(\v2\x11.game.v1.RoomViewH\x00R\broomView\x121\n" +
	"\amessage\x18\x03 \x01(\v2\x15.game.v1.MessageEventH\x00R\amessage\x123\n" +
	"\n" +
	"room_event\x18\x04 \x01(\v2\x12.game.v1.RoomEventH\x00R\troomEvent\x126\n" +
	"\vplayer_list\x18\x05 \x01(\v2\x13.game.v1.PlayerListH\x00R\n" +
	"playerList\x120\n" +
	"\texit_list\x18\x06 \x01(\v2\x11.game.v1.ExitListH\x00R\bexitList\x12+\n" +
	"\x05error\x18\a \x01(\v2\x13.game.v1.ErrorEventH\x00R\x05error\x12;\n" +
	"\fdisconnected\x18\b \x01(\v2\x15.game.v1.DisconnectedH\x00R\fdisconnected\x12?\n" +
	"\x0echaracter_info\x18\t \x01(\v2\x16.game.v1.CharacterInfoH\x00R\rcharacterInfo\x12-\n" +
	"\bnpc_view\x18\n" +
	" \x01(\v2\x10.game.v1.NpcViewH\x00R\anpcViewB\t\n" +
	"\apayload\"\xa9\x01\n" +
	"\x10JoinWorldRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\x03R\vcharacterId\x12%\n" +
	"\x0echaracter_name\x18\x04 \x01(\tR\rcharacterName\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x05 \x01(\x05R\tcurrentHp\"+\n" +
	"\vMoveRequest\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\"\r\n" +
	"\vLookRequest\"&\n" +
	"\n" +
	"SayRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\fEmoteRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"\f\n" +
	"\n" +
	"WhoRequest\"\x0e\n" +
	"\fExitsRequest\"\r\n" +
	"\vQuitRequest\"\xc4\x01\n" +
	"\bRoomView\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x05exits\x18\x04 \x03(\v2\x11.game.v1.ExitInfoR\x05exits\x12\x18\n" +
	"\aplayers\x18\x05 \x03(\tR\aplayers\x12$\n" +
	"\x04npcs\x18\x06 \x03(\v2\x10.game.v1.NpcInfoR\x04npcs\"~\n" +
	"\bExitInfo\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12$\n" +
	"\x0etarget_room_id\x18\x02 \x01(\tR\ftargetRoomId\x12\x16\n" +
	"\x06locked\x18\x03 \x01(\bR\x06locked\x12\x16\n" +
	"\x06hidden\x18\x04 \x01(\bR\x06hidden\"j\n" +
	"\fMessageEvent\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.game.v1.MessageTypeR\x04type\"m\n" +
	"\tRoomEvent\x12\x16\n" +
	"\x06player\x18\x01 \x01(\tR\x06player\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.game.v1.RoomEventTypeR\x04type\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\"E\n" +
	"\n" +
	"PlayerList\x12\x1d\n" +
	"\n" +
	"room_title\x18\x01 \x01(\tR\troomTitle\x12\x18\n" +
	"\aplayers\x18\x02 \x03(\tR\aplayers\"3\n" +
	"\bExitList\x12'\n" +
	"\x05exits\x18\x01 \x03(\v2\x11.game.v1.ExitInfoR\x05exits\"&\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\fDisconnected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x96\x03\n" +
	"\rCharacterInfo\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\x06 \x01(\x05R\n" +
	"experience\x12\x15\n" +
	"\x06max_hp\x18\a \x01(\x05R\x05maxHp\x12\x1d\n" +
	"\n" +
	"current_hp\x18\b \x01(\x05R\tcurrentHp\x12\x1a\n" +
	"\bstrength\x18\t \x01(\x05R\bstrength\x12\x1c\n" +
	"\tdexterity\x18\n" +
	" \x01(\x05R\tdexterity\x12\"\n" +
	"\fconstitution\x18\v \x01(\x05R\fconstitution\x12\"\n" +
	"\fintelligence\x18\f \x01(\x05R\fintelligence\x12\x16\n" +
	"\x06wisdom\x18\r \x01(\x05R\x06wisdom\x12\x1a\n" +
	"\bcharisma\x18\x0e \x01(\x05R\bcharisma\">\n" +
	"\aNpcInfo\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\x0eExamineRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\xa5\x01\n" +
	"\aNpcView\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x12health_description\x18\x04 \x01(\tR\x11healthDescription\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level*Y\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MESSAGE_TYPE_SAY\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_EMOTE\x10\x02*h\n" +
	"\rRoomEventType\x12\x1f\n" +
	"\x1bROOM_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ROOM_EVENT_TYPE_ARRIVE\x10\x01\x12\x1a\n" +
	"\x16ROOM_EVENT_TYPE_DEPART\x10\x022J\n" +
	"\vGameService\x12;\n" +
	"\aSession\x12\x16.game.v1.ClientMessage\x1a\x14.game.v1.ServerEvent(\x010\x01B:Z8github.com/cory-johannsen/mud/internal/gameserver/gamev1b\x06proto3"

var (
	file_game_v1_game_proto_rawDescOnce sync.Once
	file_game_v1_game_proto_rawDescData []byte
)

func file_game_v1_game_proto_rawDescGZIP() []byte {
	file_game_v1_game_proto_rawDescOnce.Do(func() {
		file_game_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_v1_game_proto_rawDesc), len(file_game_v1_game_proto_rawDesc)))
	})
	return file_game_v1_game_proto_rawDescData
}

var file_game_v1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_game_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_game_v1_game_proto_goTypes = []any{
	(MessageType)(0),         // 0: game.v1.MessageType
	(RoomEventType)(0),       // 1: game.v1.RoomEventType
	(*ClientMessage)(nil),    // 2: game.v1.ClientMessage
	(*ServerEvent)(nil),      // 3: game.v1.ServerEvent
	(*JoinWorldRequest)(nil), // 4: game.v1.JoinWorldRequest
	(*MoveRequest)(nil),      // 5: game.v1.MoveRequest
	(*LookRequest)(nil),      // 6: game.v1.LookRequest
	(*SayRequest)(nil),       // 7: game.v1.SayRequest
	(*EmoteRequest)(nil),     // 8: game.v1.EmoteRequest
	(*WhoRequest)(nil),       // 9: game.v1.WhoRequest
	(*ExitsRequest)(nil),     // 10: game.v1.ExitsRequest
	(*QuitRequest)(nil),      // 11: game.v1.QuitRequest
	(*RoomView)(nil),         // 12: game.v1.RoomView
	(*ExitInfo)(nil),         // 13: game.v1.ExitInfo
	(*MessageEvent)(nil),     // 14: game.v1.MessageEvent
	(*RoomEvent)(nil),        // 15: game.v1.RoomEvent
	(*PlayerList)(nil),       // 16: game.v1.PlayerList
	(*ExitList)(nil),         // 17: game.v1.ExitList
	(*ErrorEvent)(nil),       // 18: game.v1.ErrorEvent
	(*Disconnected)(nil),     // 19: game.v1.Disconnected
	(*CharacterInfo)(nil),    // 20: game.v1.CharacterInfo
	(*NpcInfo)(nil),          // 21: game.v1.NpcInfo
	(*ExamineRequest)(nil),   // 22: game.v1.ExamineRequest
	(*NpcView)(nil),          // 23: game.v1.NpcView
}
var file_game_v1_game_proto_depIdxs = []int32{
	4,  // 0: game.v1.ClientMessage.join_world:type_name -> game.v1.JoinWorldRequest
	5,  // 1: game.v1.ClientMessage.move:type_name -> game.v1.MoveRequest
	6,  // 2: game.v1.ClientMessage.look:type_name -> game.v1.LookRequest
	7,  // 3: game.v1.ClientMessage.say:type_name -> game.v1.SayRequest
	8,  // 4: game.v1.ClientMessage.emote:type_name -> game.v1.EmoteRequest
	9,  // 5: game.v1.ClientMessage.who:type_name -> game.v1.WhoRequest
	10, // 6: game.v1.ClientMessage.exits:type_name -> game.v1.ExitsRequest
	11, // 7: game.v1.ClientMessage.quit:type_name -> game.v1.QuitRequest
	22, // 8: game.v1.ClientMessage.examine:type_name -> game.v1.ExamineRequest
	12, // 9: game.v1.ServerEvent.room_view:type_name -> game.v1.RoomView
	14, // 10: game.v1.ServerEvent.message:type_name -> game.v1.MessageEvent
	15, // 11: game.v1.ServerEvent.room_event:type_name -> game.v1.RoomEvent
	16, // 12: game.v1.ServerEvent.player_list:type_name -> game.v1.PlayerList
	17, // 13: game.v1.ServerEvent.exit_list:type_name -> game.v1.ExitList
	18, // 14: game.v1.ServerEvent.error:type_name -> game.v1.ErrorEvent
	19, // 15: game.v1.ServerEvent.disconnected:type_name -> game.v1.Disconnected
	20, // 16: game.v1.ServerEvent.character_info:type_name -> game.v1.CharacterInfo
	23, // 17: game.v1.ServerEvent.npc_view:type_name -> game.v1.NpcView
	13, // 18: game.v1.RoomView.exits:type_name -> game.v1.ExitInfo
	21, // 19: game.v1.RoomView.npcs:type_name -> game.v1.NpcInfo
	0,  // 20: game.v1.MessageEvent.type:type_name -> game.v1.MessageType
	1,  // 21: game.v1.RoomEvent.type:type_name -> game.v1.RoomEventType
	13, // 22: game.v1.ExitList.exits:type_name -> game.v1.ExitInfo
	2,  // 23: game.v1.GameService.Session:input_type -> game.v1.ClientMessage
	3,  // 24: game.v1.GameService.Session:output_type -> game.v1.ServerEvent
	24, // [24:25] is the sub-list for method output_type
	23, // [23:24] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_game_v1_game_proto_init() }
func file_game_v1_game_proto_init() {
	if File_game_v1_game_proto != nil {
		return
	}
	file_game_v1_game_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_JoinWorld)(nil),
		(*ClientMessage_Move)(nil),
		(*ClientMessage_Look)(nil),
		(*ClientMessage_Say)(nil),
		(*ClientMessage_Emote)(nil),
		(*ClientMessage_Who)(nil),
		(*ClientMessage_Exits)(nil),
		(*ClientMessage_Quit)(nil),
		(*ClientMessage_Examine)(nil),
	}
	file_game_v1_game_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerEvent_RoomView)(nil),
		(*ServerEvent_Message)(nil),
		(*ServerEvent_RoomEvent)(nil),
		(*ServerEvent_PlayerList)(nil),
		(*ServerEvent_ExitList)(nil),
		(*ServerEvent_Error)(nil),
		(*ServerEvent_Disconnected)(nil),
		(*ServerEvent_CharacterInfo)(nil),
		(*ServerEvent_NpcView)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_v1_game_proto_rawDesc), len(file_game_v1_game_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_v1_game_proto_goTypes,
		DependencyIndexes: file_game_v1_game_proto_depIdxs,
		EnumInfos:         file_game_v1_game_proto_enumTypes,
		MessageInfos:      file_game_v1_game_proto_msgTypes,
	}.Build()
	File_game_v1_game_proto = out.File
	file_game_v1_game_proto_goTypes = nil
	file_game_v1_game_proto_depIdxs = nil
}
