// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.5
// source: game/v1/game.proto

package gamev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_Session_FullMethodName               = "/game.v1.GameService/Session"
	GameService_AdminListSessions_FullMethodName     = "/game.v1.GameService/AdminListSessions"
	GameService_AdminKickPlayer_FullMethodName       = "/game.v1.GameService/AdminKickPlayer"
	GameService_AdminMessagePlayer_FullMethodName    = "/game.v1.GameService/AdminMessagePlayer"
	GameService_AdminTeleportPlayer_FullMethodName   = "/game.v1.GameService/AdminTeleportPlayer"
	GameService_AdminListZones_FullMethodName        = "/game.v1.GameService/AdminListZones"
	GameService_AdminListRooms_FullMethodName        = "/game.v1.GameService/AdminListRooms"
	GameService_AdminUpdateRoom_FullMethodName       = "/game.v1.GameService/AdminUpdateRoom"
	GameService_AdminListNPCTemplates_FullMethodName = "/game.v1.GameService/AdminListNPCTemplates"
	GameService_AdminSpawnNPC_FullMethodName         = "/game.v1.GameService/AdminSpawnNPC"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameService provides bidirectional streaming between the Telnet frontend
// and the Pitaya-powered game backend.
type GameServiceClient interface {
	// Session establishes a bidirectional stream for a single player session.
	// The client sends commands; the server sends events.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerEvent], error)
	// Admin RPCs — unary, require admin role on the server side.
	AdminListSessions(ctx context.Context, in *AdminListSessionsRequest, opts ...grpc.CallOption) (*AdminListSessionsResponse, error)
	AdminKickPlayer(ctx context.Context, in *AdminKickRequest, opts ...grpc.CallOption) (*AdminKickResponse, error)
	AdminMessagePlayer(ctx context.Context, in *AdminMessageRequest, opts ...grpc.CallOption) (*AdminMessageResponse, error)
	AdminTeleportPlayer(ctx context.Context, in *AdminTeleportRequest, opts ...grpc.CallOption) (*AdminTeleportResponse, error)
	// World admin RPCs.
	AdminListZones(ctx context.Context, in *AdminListZonesRequest, opts ...grpc.CallOption) (*AdminListZonesResponse, error)
	AdminListRooms(ctx context.Context, in *AdminListRoomsRequest, opts ...grpc.CallOption) (*AdminListRoomsResponse, error)
	AdminUpdateRoom(ctx context.Context, in *AdminUpdateRoomRequest, opts ...grpc.CallOption) (*AdminUpdateRoomResponse, error)
	// NPC admin RPCs.
	AdminListNPCTemplates(ctx context.Context, in *AdminListNPCTemplatesRequest, opts ...grpc.CallOption) (*AdminListNPCTemplatesResponse, error)
	AdminSpawnNPC(ctx context.Context, in *AdminSpawnNPCRequest, opts ...grpc.CallOption) (*AdminSpawnNPCResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameService_ServiceDesc.Streams[0], GameService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameService_SessionClient = grpc.BidiStreamingClient[ClientMessage, ServerEvent]

func (c *gameServiceClient) AdminListSessions(ctx context.Context, in *AdminListSessionsRequest, opts ...grpc.CallOption) (*AdminListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListSessionsResponse)
	err := c.cc.Invoke(ctx, GameService_AdminListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AdminKickPlayer(ctx context.Context, in *AdminKickRequest, opts ...grpc.CallOption) (*AdminKickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminKickResponse)
	err := c.cc.Invoke(ctx, GameService_AdminKickPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AdminMessagePlayer(ctx context.Context, in *AdminMessageRequest, opts ...grpc.CallOption) (*AdminMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminMessageResponse)
	err := c.cc.Invoke(ctx, GameService_AdminMessagePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AdminTeleportPlayer(ctx context.Context, in *AdminTeleportRequest, opts ...grpc.CallOption) (*AdminTeleportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminTeleportResponse)
	err := c.cc.Invoke(ctx, GameService_AdminTeleportPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AdminListZones(ctx context.Context, in *AdminListZonesRequest, opts ...grpc.CallOption) (*AdminListZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListZonesResponse)
	err := c.cc.Invoke(ctx, GameService_AdminListZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AdminListRooms(ctx context.Context, in *AdminListRoomsRequest, opts ...grpc.CallOption) (*AdminListRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListRoomsResponse)
	err := c.cc.Invoke(ctx, GameService_AdminListRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AdminUpdateRoom(ctx context.Context, in *AdminUpdateRoomRequest, opts ...grpc.CallOption) (*AdminUpdateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdateRoomResponse)
	err := c.cc.Invoke(ctx, GameService_AdminUpdateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AdminListNPCTemplates(ctx context.Context, in *AdminListNPCTemplatesRequest, opts ...grpc.CallOption) (*AdminListNPCTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListNPCTemplatesResponse)
	err := c.cc.Invoke(ctx, GameService_AdminListNPCTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AdminSpawnNPC(ctx context.Context, in *AdminSpawnNPCRequest, opts ...grpc.CallOption) (*AdminSpawnNPCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminSpawnNPCResponse)
	err := c.cc.Invoke(ctx, GameService_AdminSpawnNPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
//
// GameService provides bidirectional streaming between the Telnet frontend
// and the Pitaya-powered game backend.
type GameServiceServer interface {
	// Session establishes a bidirectional stream for a single player session.
	// The client sends commands; the server sends events.
	Session(grpc.BidiStreamingServer[ClientMessage, ServerEvent]) error
	// Admin RPCs — unary, require admin role on the server side.
	AdminListSessions(context.Context, *AdminListSessionsRequest) (*AdminListSessionsResponse, error)
	AdminKickPlayer(context.Context, *AdminKickRequest) (*AdminKickResponse, error)
	AdminMessagePlayer(context.Context, *AdminMessageRequest) (*AdminMessageResponse, error)
	AdminTeleportPlayer(context.Context, *AdminTeleportRequest) (*AdminTeleportResponse, error)
	// World admin RPCs.
	AdminListZones(context.Context, *AdminListZonesRequest) (*AdminListZonesResponse, error)
	AdminListRooms(context.Context, *AdminListRoomsRequest) (*AdminListRoomsResponse, error)
	AdminUpdateRoom(context.Context, *AdminUpdateRoomRequest) (*AdminUpdateRoomResponse, error)
	// NPC admin RPCs.
	AdminListNPCTemplates(context.Context, *AdminListNPCTemplatesRequest) (*AdminListNPCTemplatesResponse, error)
	AdminSpawnNPC(context.Context, *AdminSpawnNPCRequest) (*AdminSpawnNPCResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) Session(grpc.BidiStreamingServer[ClientMessage, ServerEvent]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedGameServiceServer) AdminListSessions(context.Context, *AdminListSessionsRequest) (*AdminListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListSessions not implemented")
}
func (UnimplementedGameServiceServer) AdminKickPlayer(context.Context, *AdminKickRequest) (*AdminKickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminKickPlayer not implemented")
}
func (UnimplementedGameServiceServer) AdminMessagePlayer(context.Context, *AdminMessageRequest) (*AdminMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminMessagePlayer not implemented")
}
func (UnimplementedGameServiceServer) AdminTeleportPlayer(context.Context, *AdminTeleportRequest) (*AdminTeleportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminTeleportPlayer not implemented")
}
func (UnimplementedGameServiceServer) AdminListZones(context.Context, *AdminListZonesRequest) (*AdminListZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListZones not implemented")
}
func (UnimplementedGameServiceServer) AdminListRooms(context.Context, *AdminListRoomsRequest) (*AdminListRoomsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListRooms not implemented")
}
func (UnimplementedGameServiceServer) AdminUpdateRoom(context.Context, *AdminUpdateRoomRequest) (*AdminUpdateRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdateRoom not implemented")
}
func (UnimplementedGameServiceServer) AdminListNPCTemplates(context.Context, *AdminListNPCTemplatesRequest) (*AdminListNPCTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListNPCTemplates not implemented")
}
func (UnimplementedGameServiceServer) AdminSpawnNPC(context.Context, *AdminSpawnNPCRequest) (*AdminSpawnNPCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminSpawnNPC not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call panics, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServiceServer).Session(&grpc.GenericServerStream[ClientMessage, ServerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameService_SessionServer = grpc.BidiStreamingServer[ClientMessage, ServerEvent]

func _GameService_AdminListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AdminListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AdminListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AdminListSessions(ctx, req.(*AdminListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AdminKickPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminKickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AdminKickPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AdminKickPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AdminKickPlayer(ctx, req.(*AdminKickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AdminMessagePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AdminMessagePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AdminMessagePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AdminMessagePlayer(ctx, req.(*AdminMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AdminTeleportPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminTeleportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AdminTeleportPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AdminTeleportPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AdminTeleportPlayer(ctx, req.(*AdminTeleportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AdminListZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AdminListZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AdminListZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AdminListZones(ctx, req.(*AdminListZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AdminListRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AdminListRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AdminListRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AdminListRooms(ctx, req.(*AdminListRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AdminUpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AdminUpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AdminUpdateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AdminUpdateRoom(ctx, req.(*AdminUpdateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AdminListNPCTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListNPCTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AdminListNPCTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AdminListNPCTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AdminListNPCTemplates(ctx, req.(*AdminListNPCTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AdminSpawnNPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminSpawnNPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AdminSpawnNPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AdminSpawnNPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AdminSpawnNPC(ctx, req.(*AdminSpawnNPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.v1.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminListSessions",
			Handler:    _GameService_AdminListSessions_Handler,
		},
		{
			MethodName: "AdminKickPlayer",
			Handler:    _GameService_AdminKickPlayer_Handler,
		},
		{
			MethodName: "AdminMessagePlayer",
			Handler:    _GameService_AdminMessagePlayer_Handler,
		},
		{
			MethodName: "AdminTeleportPlayer",
			Handler:    _GameService_AdminTeleportPlayer_Handler,
		},
		{
			MethodName: "AdminListZones",
			Handler:    _GameService_AdminListZones_Handler,
		},
		{
			MethodName: "AdminListRooms",
			Handler:    _GameService_AdminListRooms_Handler,
		},
		{
			MethodName: "AdminUpdateRoom",
			Handler:    _GameService_AdminUpdateRoom_Handler,
		},
		{
			MethodName: "AdminListNPCTemplates",
			Handler:    _GameService_AdminListNPCTemplates_Handler,
		},
		{
			MethodName: "AdminSpawnNPC",
			Handler:    _GameService_AdminSpawnNPC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _GameService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "game/v1/game.proto",
}
