// EffectsDrawer — duplicate-effects-handling plan Task 10.
//
// Renders the server-produced CharacterSheetView.effectsSummary block verbatim
// inside a <pre>, matching the telnet `effects` command output. The summary
// text is generated by internal/game/effect/render.EffectsBlock on the
// server, so both clients see identical output.
//
// Precondition: useGame provides state.characterSheet; sendMessage is
// available. The drawer dispatches a CharacterSheetRequest on mount if no
// sheet is cached yet.
// Postcondition: renders a header, close button, and either the effectsSummary
// string in a monospace <pre> block or a neutral empty-state line when no
// active effects are present.
import { useEffect } from 'react'
import { useGame } from '../GameContext'

// hasActiveEffects returns true when the supplied summary describes at least
// one active effect. The RenderEffectsBlock Go formatter emits
// "Effects:\n  No active effects.\n" for an empty set; any other non-blank
// content indicates active effects.
function hasActiveEffects(summary: string): boolean {
  const trimmed = summary.trim()
  if (trimmed === '') return false
  if (trimmed === 'Effects:\n  No active effects.'.trim()) return false
  // Match the exact telnet empty-set sentinel regardless of surrounding
  // whitespace variations.
  if (/no active effects/i.test(trimmed) && !/\battack\b|\bac\b|\bdamage\b|\(active\)|\(overridden/.test(trimmed)) {
    return false
  }
  return true
}

export function EffectsDrawer({ onClose }: { onClose: () => void }) {
  const { state, sendMessage } = useGame()

  useEffect(() => {
    if (!state.characterSheet) {
      sendMessage('CharacterSheetRequest', {})
    }
  }, [state.characterSheet, sendMessage])

  const sheet = state.characterSheet
  const summary = (sheet?.effectsSummary ?? sheet?.effects_summary ?? '') as string
  const active = hasActiveEffects(summary)

  return (
    <div style={{ fontFamily: 'monospace', color: '#ccc' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
        <h3 style={{ margin: 0, color: '#e0c060', fontSize: '0.95rem' }}>Active Effects</h3>
        <button
          type="button"
          aria-label="Close"
          style={{ background: 'none', border: '1px solid #444', color: '#888', cursor: 'pointer', borderRadius: 3, padding: '0.1rem 0.4rem', fontFamily: 'monospace' }}
          onClick={onClose}
        >
          ✕
        </button>
      </div>

      {!sheet && (
        <p style={{ color: '#555', fontSize: '0.82rem' }}>Loading…</p>
      )}
      {sheet && !active && (
        <p style={{ color: '#666', fontSize: '0.82rem', fontStyle: 'italic' }}>No active effects.</p>
      )}
      {sheet && active && (
        <pre
          style={{
            margin: 0,
            padding: '0.6rem 0.75rem',
            background: '#0f1420',
            border: '1px solid #1e2a3a',
            borderRadius: 4,
            color: '#cde',
            fontSize: '0.78rem',
            lineHeight: 1.4,
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-word',
          }}
        >
          {summary}
        </pre>
      )}
    </div>
  )
}
