// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/cory-johannsen/mud/internal/game/ai"
	"github.com/cory-johannsen/mud/internal/game/combat"
	"github.com/cory-johannsen/mud/internal/game/condition"
	"github.com/cory-johannsen/mud/internal/game/dice"
	"github.com/cory-johannsen/mud/internal/game/inventory"
	"github.com/cory-johannsen/mud/internal/game/mentalstate"
	"github.com/cory-johannsen/mud/internal/game/npc"
	"github.com/cory-johannsen/mud/internal/game/ruleset"
	"github.com/cory-johannsen/mud/internal/game/session"
	"github.com/cory-johannsen/mud/internal/game/substance"
	"github.com/cory-johannsen/mud/internal/game/technology"
	"github.com/cory-johannsen/mud/internal/game/world"
	"github.com/cory-johannsen/mud/internal/gameserver"
	"github.com/cory-johannsen/mud/internal/scripting"
	"github.com/cory-johannsen/mud/internal/storage/postgres"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// Initialize is the wire-generated injector for the gameserver binary.
func Initialize(ctx context.Context, cfg *AppConfig, clock *gameserver.GameClock, logger *zap.Logger) (*App, error) {
	databaseConfig := AppConfigToDatabase(cfg)
	pool, err := postgres.NewPool(ctx, databaseConfig)
	if err != nil {
		return nil, err
	}
	pgxpoolPool := postgres.PoolDB(pool)
	characterRepository := postgres.NewCharacterRepository(pgxpoolPool)
	accountRepository := postgres.NewAccountRepository(pgxpoolPool)
	accountRepoAdapter := gameserver.NewAccountRepoAdapter(accountRepository)
	characterSkillsRepository := postgres.NewCharacterSkillsRepository(pgxpoolPool)
	characterProficienciesRepository := postgres.NewCharacterProficienciesRepository(pgxpoolPool)
	characterFeatsRepository := postgres.NewCharacterFeatsRepository(pgxpoolPool)
	characterClassFeaturesRepository := postgres.NewCharacterClassFeaturesRepository(pgxpoolPool)
	characterFeatureChoicesRepo := postgres.NewCharacterFeatureChoicesRepo(pgxpoolPool)
	postgresCharacterAbilityBoostsRepository := postgres.NewCharacterAbilityBoostsRepository(pgxpoolPool)
	characterHardwiredTechRepository := postgres.NewCharacterHardwiredTechRepository(pgxpoolPool)
	characterPreparedTechRepository := postgres.NewCharacterPreparedTechRepository(pgxpoolPool)
	characterSpontaneousTechRepository := postgres.NewCharacterSpontaneousTechRepository(pgxpoolPool)
	characterInnateTechRepository := postgres.NewCharacterInnateTechRepository(pgxpoolPool)
	characterSpontaneousUsePoolRepository := postgres.NewCharacterSpontaneousUsePoolRepository(pgxpoolPool)
	wantedRepository := postgres.NewWantedRepository(pgxpoolPool)
	automapRepository := postgres.NewAutomapRepository(pgxpoolPool)
	storageDeps := gameserver.StorageDeps{
		CharRepo:               characterRepository,
		AccountRepo:            accountRepoAdapter,
		SkillsRepo:             characterSkillsRepository,
		ProficienciesRepo:      characterProficienciesRepository,
		FeatsRepo:              characterFeatsRepository,
		ClassFeaturesRepo:      characterClassFeaturesRepository,
		FeatureChoicesRepo:     characterFeatureChoicesRepo,
		AbilityBoostsRepo:      postgresCharacterAbilityBoostsRepository,
		HardwiredTechRepo:      characterHardwiredTechRepository,
		PreparedTechRepo:       characterPreparedTechRepository,
		SpontaneousTechRepo:    characterSpontaneousTechRepository,
		InnateTechRepo:         characterInnateTechRepository,
		SpontaneousUsePoolRepo: characterSpontaneousUsePoolRepository,
		WantedRepo:             wantedRepository,
		AutomapRepo:            automapRepository,
	}
	worldDir := cfg.ZonesDir
	manager, err := world.NewManagerFromDir(worldDir, logger)
	if err != nil {
		return nil, err
	}
	conditionsDir := cfg.ConditionsDir
	mentalConditionsDir := cfg.MentalCondDir
	conditionRegistry, err := condition.NewRegistryFromDir(conditionsDir, mentalConditionsDir, logger)
	if err != nil {
		return nil, err
	}
	weaponsDir := cfg.WeaponsDir
	itemsDir := cfg.ItemsDir
	explosivesDir := cfg.ExplosivesDir
	armorsDir := cfg.ArmorsDir
	registry, err := inventory.NewRegistryFromDirs(weaponsDir, itemsDir, explosivesDir, armorsDir, conditionRegistry, logger)
	if err != nil {
		return nil, err
	}
	npcManager := npc.NewWiredManager(registry)
	npCsDir := cfg.NPCsDir
	v, err := npc.LoadTemplatesFromDir(npCsDir, logger)
	if err != nil {
		return nil, err
	}
	respawnManager, err := npc.NewPopulatedRespawnManager(v, manager, npcManager, logger)
	if err != nil {
		return nil, err
	}
	floorManager := inventory.NewFloorManager()
	roomEquipmentManager := inventory.NewSeededRoomEquipmentManager(manager, logger)
	techContentDir := cfg.TechContentDir
	technologyRegistry, err := technology.NewRegistryFromDir(techContentDir, logger)
	if err != nil {
		return nil, err
	}
	// Load equipment set registry (REQ-EM-29/35).
	knownConditionIDs := make(map[string]bool)
	for _, cd := range conditionRegistry.All() {
		knownConditionIDs[cd.ID] = true
	}
	setRegistry, err := inventory.LoadSetRegistry(cfg.SetsDir, knownConditionIDs)
	if err != nil {
		return nil, fmt.Errorf("loading set registry: %w", err)
	}
	// Load substance registry (REQ-AH-3).
	substancesDir := cfg.SubstancesDir
	substanceRegistry, err := substance.LoadDirectory(substancesDir)
	if err != nil {
		return nil, fmt.Errorf("loading substance registry: %w", err)
	}
	// Cross-validate substance condition references against condition registry (REQ-AH-4A).
	if cvErr := substanceRegistry.CrossValidate(knownConditionIDs); cvErr != nil {
		return nil, fmt.Errorf("substance cross-validation failed: %w", cvErr)
	}
	aiRegistry := ai.NewEmptyRegistry()
	skillsFile := cfg.SkillsFile
	v2, err := ruleset.LoadAllSkills(skillsFile, logger)
	if err != nil {
		return nil, err
	}
	featsFile := cfg.FeatsFile
	v3, err := ruleset.LoadAllFeats(featsFile, logger)
	if err != nil {
		return nil, err
	}
	classFeaturesFile := cfg.ClassFeatsFile
	v4, err := ruleset.LoadAllClassFeatures(classFeaturesFile, logger)
	if err != nil {
		return nil, err
	}
	featRegistry := ruleset.NewFeatRegistryFromFeats(v3)
	classFeatureRegistry := ruleset.NewClassFeatureRegistryFromFeatures(v4)
	jobsDir := cfg.JobsDir
	jobRegistry, err := ruleset.NewJobRegistryFromDir(jobsDir, logger)
	if err != nil {
		return nil, err
	}
	archetypesDir := cfg.ArchetypesDir
	v5, err := ruleset.LoadArchetypeMap(archetypesDir, logger)
	if err != nil {
		return nil, err
	}
	regionsDir := cfg.RegionsDir
	v6, err := ruleset.LoadRegionMap(regionsDir, logger)
	if err != nil {
		return nil, err
	}
	scriptRoot := cfg.ScriptRoot
	condScriptDir := cfg.CondScriptDir
	aiScriptDir := cfg.AIScriptDir
	roller := dice.NewCryptoRoller(logger)
	scriptingManager, err := scripting.NewManagerFromDirs(scriptRoot, condScriptDir, aiScriptDir, roller, logger)
	if err != nil {
		return nil, err
	}
	engine := combat.NewEngine()
	mentalstateManager := mentalstate.NewManager()
	loadoutsDir := cfg.LoadoutsDir
	contentDeps := gameserver.ContentDeps{
		WorldMgr:             manager,
		NpcMgr:               npcManager,
		RespawnMgr:           respawnManager,
		InvRegistry:          registry,
		FloorMgr:             floorManager,
		RoomEquipMgr:         roomEquipmentManager,
		TechRegistry:         technologyRegistry,
		CondRegistry:         conditionRegistry,
		AIRegistry:           aiRegistry,
		AllSkills:            v2,
		AllFeats:             v3,
		ClassFeatures:        v4,
		FeatRegistry:         featRegistry,
		ClassFeatureRegistry: classFeatureRegistry,
		JobRegistry:          jobRegistry,
		ArchetypeMap:         v5,
		RegionMap:            v6,
		ScriptMgr:            scriptingManager,
		DiceRoller:           roller,
		CombatEngine:         engine,
		MentalStateMgr:       mentalstateManager,
		LoadoutsDir:          loadoutsDir,
		SetRegistry:          setRegistry,
		SubstanceRegistry:    substanceRegistry,
	}
	sessionManager := gameserver.NewSessionManager()
	worldHandler := gameserver.NewWorldHandlerProvider(manager, sessionManager, npcManager, clock, roomEquipmentManager, registry)
	chatHandler := gameserver.NewChatHandlerProvider(sessionManager)
	npcHandler := gameserver.NewNPCHandlerProvider(npcManager, sessionManager)
	roundDurationMs := cfg.RoundDurationMs
	combatHandler := gameserver.NewCombatHandlerProvider(engine, npcManager, sessionManager, roller, roundDurationMs, conditionRegistry, manager, scriptingManager, registry, aiRegistry, respawnManager, floorManager, mentalstateManager, logger)
	actionHandler := gameserver.NewActionHandlerProvider(sessionManager, classFeatureRegistry, conditionRegistry, npcManager, combatHandler, characterRepository, roller, logger)
	handlerDeps := gameserver.HandlerDeps{
		WorldHandler:  worldHandler,
		ChatHandler:   chatHandler,
		NPCHandler:    npcHandler,
		CombatHandler: combatHandler,
		ActionHandler: actionHandler,
	}
	commandRegistry, err := gameserver.NewCommandRegistry(v4)
	if err != nil {
		return nil, err
	}
	calendarRepo := postgres.NewCalendarRepo(pgxpoolPool)
	gameCalendar, err := gameserver.NewGameCalendarFromRepo(calendarRepo, clock)
	if err != nil {
		return nil, err
	}
	gameServiceServer := gameserver.NewGameServiceServer(storageDeps, contentDeps, handlerDeps, sessionManager, commandRegistry, gameCalendar, logger)
	regenManager := gameserver.NewRegenManagerProvider(sessionManager, npcManager, combatHandler, characterRepository, logger)
	aiTickInterval := cfg.AITickInterval
	zoneTickManager := gameserver.NewZoneTickManagerProvider(aiTickInterval)
	characterProgressRepository := postgres.NewCharacterProgressRepository(pgxpoolPool)
	app := &App{
		GRPCService:   gameServiceServer,
		CombatHandler: combatHandler,
		RegenMgr:      regenManager,
		ZoneTickMgr:   zoneTickManager,
		AIRegistry:    aiRegistry,
		GameCalendar:  gameCalendar,
		Pool:          pool,
		ScriptMgr:     scriptingManager,
		WorldMgr:      manager,
		NpcMgr:        npcManager,
		CombatEngine:  engine,
		SessMgr:       sessionManager,
		AutomapRepo:   automapRepository,
		InvRegistry:   registry,
		RespawnMgr:    respawnManager,
		RoomEquipMgr:  roomEquipmentManager,
		CharRepo:      characterRepository,
		ProgressRepo:  characterProgressRepository,
	}
	return app, nil
}

// wire.go:

// App holds all top-level components for the gameserver binary.
type App struct {
	GRPCService   *gameserver.GameServiceServer
	CombatHandler *gameserver.CombatHandler
	RegenMgr      *gameserver.RegenManager
	ZoneTickMgr   *gameserver.ZoneTickManager
	AIRegistry    *ai.Registry
	GameCalendar  *gameserver.GameCalendar
	Pool          *postgres.Pool
	ScriptMgr     *scripting.Manager
	WorldMgr      *world.Manager
	NpcMgr        *npc.Manager
	CombatEngine  *combat.Engine
	SessMgr       *session.Manager
	AutomapRepo   *postgres.AutomapRepository
	InvRegistry   *inventory.Registry
	RespawnMgr    *npc.RespawnManager
	RoomEquipMgr  *inventory.RoomEquipmentManager
	CharRepo      *postgres.CharacterRepository
	ProgressRepo  *postgres.CharacterProgressRepository
}
