// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/cory-johannsen/mud/internal/game/ai"
	"github.com/cory-johannsen/mud/internal/game/combat"
	"github.com/cory-johannsen/mud/internal/game/condition"
	"github.com/cory-johannsen/mud/internal/game/crafting"
	"github.com/cory-johannsen/mud/internal/game/dice"
	"github.com/cory-johannsen/mud/internal/game/downtime"
	"github.com/cory-johannsen/mud/internal/game/faction"
	"github.com/cory-johannsen/mud/internal/game/quest"
	"github.com/cory-johannsen/mud/internal/game/inventory"
	"github.com/cory-johannsen/mud/internal/game/mentalstate"
	"github.com/cory-johannsen/mud/internal/game/npc"
	"github.com/cory-johannsen/mud/internal/game/ruleset"
	"github.com/cory-johannsen/mud/internal/game/session"
	"github.com/cory-johannsen/mud/internal/game/substance"
	"github.com/cory-johannsen/mud/internal/game/technology"
	"github.com/cory-johannsen/mud/internal/game/world"
	"github.com/cory-johannsen/mud/internal/gameserver"
	"github.com/cory-johannsen/mud/internal/scripting"
	"github.com/cory-johannsen/mud/internal/storage/postgres"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// Initialize is the wire-generated injector for the gameserver binary.
func Initialize(ctx context.Context, cfg *AppConfig, clock *gameserver.GameClock, logger *zap.Logger) (*App, error) {
	databaseConfig := AppConfigToDatabase(cfg)
	pool, err := postgres.NewPool(ctx, databaseConfig)
	if err != nil {
		return nil, err
	}
	pgxpoolPool := postgres.PoolDB(pool)
	characterRepository := postgres.NewCharacterRepository(pgxpoolPool)
	accountRepository := postgres.NewAccountRepository(pgxpoolPool)
	accountRepoAdapter := gameserver.NewAccountRepoAdapter(accountRepository)
	characterSkillsRepository := postgres.NewCharacterSkillsRepository(pgxpoolPool)
	characterProficienciesRepository := postgres.NewCharacterProficienciesRepository(pgxpoolPool)
	characterFeatsRepository := postgres.NewCharacterFeatsRepository(pgxpoolPool)
	characterClassFeaturesRepository := postgres.NewCharacterClassFeaturesRepository(pgxpoolPool)
	characterFeatureChoicesRepo := postgres.NewCharacterFeatureChoicesRepo(pgxpoolPool)
	postgresCharacterAbilityBoostsRepository := postgres.NewCharacterAbilityBoostsRepository(pgxpoolPool)
	characterHardwiredTechRepository := postgres.NewCharacterHardwiredTechRepository(pgxpoolPool)
	characterPreparedTechRepository := postgres.NewCharacterPreparedTechRepository(pgxpoolPool)
	characterKnownTechRepository := postgres.NewCharacterKnownTechRepository(pgxpoolPool)
	characterInnateTechRepository := postgres.NewCharacterInnateTechRepository(pgxpoolPool)
	characterSpontaneousUsePoolRepository := postgres.NewCharacterSpontaneousUsePoolRepository(pgxpoolPool)
	wantedRepository := postgres.NewWantedRepository(pgxpoolPool)
	automapRepository := postgres.NewAutomapRepository(pgxpoolPool)
	factionRepRepository := postgres.NewFactionRepRepository(pgxpoolPool)
	characterMaterialsRepository := postgres.NewCharacterMaterialsRepository(pgxpoolPool)
	characterDowntimeRepository := postgres.NewCharacterDowntimeRepository(pgxpoolPool)
	characterDowntimeQueueRepository := postgres.NewCharacterDowntimeQueueRepository(pgxpoolPool)
	characterFeatLevelGrantsRepository := postgres.NewCharacterFeatLevelGrantsRepository(pgxpoolPool)
	questRepository := postgres.NewQuestRepository(pgxpoolPool)
	storageDeps := gameserver.StorageDeps{
		CharRepo:               characterRepository,
		AccountRepo:            accountRepoAdapter,
		SkillsRepo:             characterSkillsRepository,
		ProficienciesRepo:      characterProficienciesRepository,
		FeatsRepo:              characterFeatsRepository,
		FeatLevelGrantsRepo:    characterFeatLevelGrantsRepository,
		ClassFeaturesRepo:      characterClassFeaturesRepository,
		FeatureChoicesRepo:     characterFeatureChoicesRepo,
		AbilityBoostsRepo:      postgresCharacterAbilityBoostsRepository,
		HardwiredTechRepo:      characterHardwiredTechRepository,
		PreparedTechRepo:       characterPreparedTechRepository,
		KnownTechRepo:          characterKnownTechRepository,
		InnateTechRepo:         characterInnateTechRepository,
		SpontaneousUsePoolRepo: characterSpontaneousUsePoolRepository,
		WantedRepo:             wantedRepository,
		AutomapRepo:            automapRepository,
		DetainedUntilRepo:      characterRepository,
		FactionRepRepo:         factionRepRepository,
		MaterialRepo:           characterMaterialsRepository,
		DowntimeRepo:           characterDowntimeRepository,
		DowntimeQueueRepo:      characterDowntimeQueueRepository,
		QuestRepo:              questRepository,
	}
	worldDir := cfg.ZonesDir
	manager, err := world.NewManagerFromDir(worldDir, logger)
	if err != nil {
		return nil, err
	}
	conditionsDir := cfg.ConditionsDir
	mentalConditionsDir := cfg.MentalCondDir
	conditionRegistry, err := condition.NewRegistryFromDir(conditionsDir, mentalConditionsDir, logger)
	if err != nil {
		return nil, err
	}
	weaponsDir := cfg.WeaponsDir
	itemsDir := cfg.ItemsDir
	explosivesDir := cfg.ExplosivesDir
	armorsDir := cfg.ArmorsDir
	preciousMaterialsDir := cfg.PreciousMaterialsDir
	registry, err := inventory.NewRegistryFromDirs(weaponsDir, itemsDir, explosivesDir, armorsDir, preciousMaterialsDir, conditionRegistry, logger)
	if err != nil {
		return nil, err
	}
	npcManager := npc.NewWiredManager(registry)
	npCsDir := cfg.NPCsDir
	v, err := npc.LoadTemplatesFromDir(npCsDir, logger)
	if err != nil {
		return nil, err
	}
	respawnManager, err := npc.NewPopulatedRespawnManager(v, manager, npcManager, logger)
	if err != nil {
		return nil, err
	}
	floorManager := inventory.NewFloorManager()
	roomEquipmentManager := inventory.NewSeededRoomEquipmentManager(manager, logger)
	techContentDir := cfg.TechContentDir
	technologyRegistry, err := technology.NewRegistryFromDir(techContentDir, logger)
	if err != nil {
		return nil, err
	}
	// Load equipment set registry (REQ-EM-29/35).
	knownConditionIDs := make(map[string]bool)
	for _, cd := range conditionRegistry.All() {
		knownConditionIDs[cd.ID] = true
	}
	setRegistry, err := inventory.LoadSetRegistry(cfg.SetsDir, knownConditionIDs)
	if err != nil {
		return nil, fmt.Errorf("loading set registry: %w", err)
	}
	// Load substance registry (REQ-AH-3).
	substancesDir := cfg.SubstancesDir
	substanceRegistry, err := substance.LoadDirectory(substancesDir)
	if err != nil {
		return nil, fmt.Errorf("loading substance registry: %w", err)
	}
	// Cross-validate substance condition references against condition registry (REQ-AH-4A).
	if cvErr := substanceRegistry.CrossValidate(knownConditionIDs); cvErr != nil {
		return nil, fmt.Errorf("substance cross-validation failed: %w", cvErr)
	}
	aiRegistry := ai.NewEmptyRegistry()
	skillsFile := cfg.SkillsFile
	v2, err := ruleset.LoadAllSkills(skillsFile, logger)
	if err != nil {
		return nil, err
	}
	featsFile := cfg.FeatsFile
	v3, err := ruleset.LoadAllFeats(featsFile, logger)
	if err != nil {
		return nil, err
	}
	classFeaturesFile := cfg.ClassFeatsFile
	v4, err := ruleset.LoadAllClassFeatures(classFeaturesFile, logger)
	if err != nil {
		return nil, err
	}
	featRegistry := ruleset.NewFeatRegistryFromFeats(v3)
	classFeatureRegistry := ruleset.NewClassFeatureRegistryFromFeatures(v4)
	jobsDir := cfg.JobsDir
	jobRegistry, err := ruleset.NewJobRegistryFromDir(jobsDir, logger)
	if err != nil {
		return nil, err
	}
	archetypesDir := cfg.ArchetypesDir
	v5, err := ruleset.LoadArchetypeMap(archetypesDir, logger)
	if err != nil {
		return nil, err
	}
	regionsDir := cfg.RegionsDir
	v6, err := ruleset.LoadRegionMap(regionsDir, logger)
	if err != nil {
		return nil, err
	}
	scriptRoot := cfg.ScriptRoot
	condScriptDir := cfg.CondScriptDir
	aiScriptDir := cfg.AIScriptDir
	roller := dice.NewCryptoRoller(logger)
	scriptingManager, err := scripting.NewManagerFromDirs(scriptRoot, condScriptDir, aiScriptDir, roller, logger)
	if err != nil {
		return nil, err
	}
	engine := combat.NewEngine()
	mentalstateManager := mentalstate.NewManager()
	loadoutsDir := cfg.LoadoutsDir
	// Load faction registry and config (optional — nil when paths are not configured).
	var factionRegistry *faction.FactionRegistry
	var factionConfig *faction.FactionConfig
	if cfg.FactionsDir != "" {
		fr, fErr := faction.ProvideRegistry(faction.FactionsDir(cfg.FactionsDir))
		if fErr != nil {
			return nil, fmt.Errorf("loading faction registry: %w", fErr)
		}
		factionRegistry = fr
	}
	if cfg.FactionConfigPath != "" {
		fc, fErr := faction.ProvideConfig(faction.FactionConfigPath(cfg.FactionConfigPath))
		if fErr != nil {
			return nil, fmt.Errorf("loading faction config: %w", fErr)
		}
		factionConfig = &fc
	}
	// Load crafting material and recipe registries (REQ-CRAFT-1/6).
	materialRegistry, err := crafting.LoadMaterialRegistry(cfg.MaterialsFile)
	if err != nil {
		return nil, fmt.Errorf("loading material registry: %w", err)
	}
	recipeRegistry, err := crafting.LoadRecipeRegistry(cfg.RecipesDir, materialRegistry, nil)
	if err != nil {
		return nil, fmt.Errorf("loading recipe registry: %w", err)
	}
	// Load downtime queue limit registry (REQ-DTQ-15: missing file is fatal).
	downtimeQueueLimitRegistry, err := downtime.LoadDowntimeQueueLimitRegistry(cfg.DowntimeQueueLimitsFile)
	if err != nil {
		return nil, fmt.Errorf("loading downtime queue limits: %w", err)
	}
	// Load quest registry (REQ-1b/1c: fatal on error).
	questRegistry, err := quest.LoadFromDir(cfg.QuestsDir)
	if err != nil {
		return nil, fmt.Errorf("loading quest registry: %w", err)
	}
	contentDeps := gameserver.ContentDeps{
		WorldMgr:             manager,
		NpcMgr:               npcManager,
		RespawnMgr:           respawnManager,
		InvRegistry:          registry,
		FloorMgr:             floorManager,
		RoomEquipMgr:         roomEquipmentManager,
		TechRegistry:         technologyRegistry,
		CondRegistry:         conditionRegistry,
		AIRegistry:           aiRegistry,
		AllSkills:            v2,
		AllFeats:             v3,
		ClassFeatures:        v4,
		FeatRegistry:         featRegistry,
		ClassFeatureRegistry: classFeatureRegistry,
		JobRegistry:          jobRegistry,
		ArchetypeMap:         v5,
		RegionMap:            v6,
		ScriptMgr:            scriptingManager,
		DiceRoller:           roller,
		CombatEngine:         engine,
		MentalStateMgr:       mentalstateManager,
		LoadoutsDir:          loadoutsDir,
		SetRegistry:          setRegistry,
		SubstanceRegistry:    substanceRegistry,
		FactionRegistry:      factionRegistry,
		FactionConfig:        factionConfig,
		MaterialRegistry:           materialRegistry,
		RecipeRegistry:             recipeRegistry,
		DowntimeQueueLimitRegistry: downtimeQueueLimitRegistry,
		QuestRegistry:              questRegistry,
	}
	sessionManager := gameserver.NewSessionManager()
	worldHandler := gameserver.NewWorldHandlerProvider(manager, sessionManager, npcManager, clock, roomEquipmentManager, registry)
	chatHandler := gameserver.NewChatHandlerProvider(sessionManager)
	npcHandler := gameserver.NewNPCHandlerProvider(npcManager, sessionManager)
	roundDurationMs := cfg.RoundDurationMs
	combatHandler := gameserver.NewCombatHandlerProvider(engine, npcManager, sessionManager, roller, roundDurationMs, conditionRegistry, manager, scriptingManager, registry, aiRegistry, respawnManager, floorManager, mentalstateManager, logger)
	actionHandler := gameserver.NewActionHandlerProvider(sessionManager, classFeatureRegistry, conditionRegistry, npcManager, combatHandler, characterRepository, roller, logger)
	handlerDeps := gameserver.HandlerDeps{
		WorldHandler:  worldHandler,
		ChatHandler:   chatHandler,
		NPCHandler:    npcHandler,
		CombatHandler: combatHandler,
		ActionHandler: actionHandler,
	}
	commandRegistry, err := gameserver.NewCommandRegistry(v4)
	if err != nil {
		return nil, err
	}
	calendarRepo := postgres.NewCalendarRepo(pgxpoolPool)
	gameCalendar, err := gameserver.NewGameCalendarFromRepo(calendarRepo, clock)
	if err != nil {
		return nil, err
	}
	gameServiceServer := gameserver.NewGameServiceServer(storageDeps, contentDeps, handlerDeps, sessionManager, commandRegistry, gameCalendar, logger)
	regenManager := gameserver.NewRegenManagerProvider(sessionManager, npcManager, combatHandler, characterRepository, logger)
	aiTickInterval := cfg.AITickInterval
	zoneTickManager := gameserver.NewZoneTickManagerProvider(aiTickInterval)
	characterProgressRepository := postgres.NewCharacterProgressRepository(pgxpoolPool)
	// Construct WeatherManager when weather content file is configured.
	var weatherManager *gameserver.WeatherManager
	if cfg.WeatherFile != "" {
		weatherTypes, wtErr := gameserver.LoadWeatherTypes(cfg.WeatherFile)
		if wtErr != nil {
			// File missing or unreadable — run without weather (e.g. e2e tests).
			logger.Warn("weather types failed to load; running without weather", zap.Error(wtErr))
			weatherTypes = nil
		}
		if weatherTypes != nil {
			postgresWeatherRepo := postgres.NewWeatherRepo(pgxpoolPool)
			weatherManager = gameserver.NewWeatherManager(postgresWeatherRepo, weatherTypes, cfg.WeatherChancePerTick, sessionManager)
			if lsErr := weatherManager.LoadState(ctx); lsErr != nil {
				return nil, fmt.Errorf("loading weather state: %w", lsErr)
			}
			weatherCh := make(chan gameserver.GameDateTime, 2)
			gameCalendar.Subscribe(weatherCh)
			go func() {
				for dt := range weatherCh {
					weatherManager.OnTick(dt)
				}
			}()
			gameServiceServer.SetWeatherManager(weatherManager)
			combatHandler.SetWeatherManager(weatherManager)
		}
	}
	app := &App{
		GRPCService:   gameServiceServer,
		CombatHandler: combatHandler,
		RegenMgr:      regenManager,
		ZoneTickMgr:   zoneTickManager,
		AIRegistry:    aiRegistry,
		GameCalendar:  gameCalendar,
		Pool:          pool,
		ScriptMgr:     scriptingManager,
		WorldMgr:      manager,
		NpcMgr:        npcManager,
		CombatEngine:  engine,
		SessMgr:       sessionManager,
		AutomapRepo:   automapRepository,
		InvRegistry:   registry,
		RespawnMgr:    respawnManager,
		RoomEquipMgr:  roomEquipmentManager,
		CharRepo:      characterRepository,
		ProgressRepo:  characterProgressRepository,
		WeatherMgr:    weatherManager,
	}
	return app, nil
}

// wire.go:

// App holds all top-level components for the gameserver binary.
type App struct {
	GRPCService   *gameserver.GameServiceServer
	CombatHandler *gameserver.CombatHandler
	RegenMgr      *gameserver.RegenManager
	ZoneTickMgr   *gameserver.ZoneTickManager
	AIRegistry    *ai.Registry
	GameCalendar  *gameserver.GameCalendar
	Pool          *postgres.Pool
	ScriptMgr     *scripting.Manager
	WorldMgr      *world.Manager
	NpcMgr        *npc.Manager
	CombatEngine  *combat.Engine
	SessMgr       *session.Manager
	AutomapRepo   *postgres.AutomapRepository
	InvRegistry   *inventory.Registry
	RespawnMgr    *npc.RespawnManager
	RoomEquipMgr  *inventory.RoomEquipmentManager
	CharRepo      *postgres.CharacterRepository
	ProgressRepo  *postgres.CharacterProgressRepository
	WeatherMgr    *gameserver.WeatherManager
}
